name: "[CI] Build and test"

on:
  pull_request:
    branches: ["main"]

  workflow_call:
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/unity-tests.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  build:
    needs: test
    uses: ./.github/workflows/unity-build.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
